version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY='
      - 'OPENAI_API_HOST='
      - 'GOOGLE_API_KEY='
      - 'GOOGLE_CSE_ID='
